# Generated by Django 4.2.4 on 2024-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_city_customer_country_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, choices=[('NY', 'New York'), ('LA', 'Los Angeles'), ('TO', 'Toronto'), ('SY', 'Sydney')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('AU', 'Australia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=2, max_length=124),
            preserve_default=False,
        ),
    ]
