# Generated by Django 4.2.4 on 2024-05-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_city_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('meru', 'Meru'), ('migori', 'Migori'), ('marsabit', 'Marsabit'), ('mombasa', 'Mombasa'), ('muranga', 'Muranga'), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, choices=[('NY', 'New York'), ('LA', 'Los Angeles'), ('TO', 'Toronto'), ('SY', 'Sydney')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
